### ISSUE TITLE
non-cluster-admin user can't get rayclusters resource

### ISSUE THREAD

**Issue by j4ckstraw** [ray-project/kuberay-helm#48]
I'm a ray developer, we deploy kuberay in kubernetes platform, cluster admin run `helm install xxx` installed kuberay-operator for us, but we account the follow error:

```bash
$ kubectl get rayclusters
Error from server (Forbidden): rayclusters.ray.io is forbidden: User "<user>" cannot list resource "rayclusters" in API group "ray.io" in the namespace "<namespace>"
```

according to https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles, may helm chart clusterrole need aggregated labels to support this.
```yaml
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
```
